# -*- coding: utf-8 -*-
"""Calcula Idade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZVJsX4ieiJrs05U_R1euulbq413rEXE
"""

# Instruções do projeto
# Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
# A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

# Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.

import datetime

ano_2022 = 2022
#Define a função
def idade ():
  recebe_nome = input("Escreva seu nome completo: ")
  recebe_nome=recebe_nome.upper()
  data_atual = datetime.datetime.now()
  ano_atual = data_atual.year
  while True:
    try:
        nascimento = int(input("Digite o ano de nascimeento: "))
        if 1922<= nascimento <=2021:
          break
    except ValueError:
      print("Você provavelmente digitou o número errado, ou sua data de nascimento é menor que 2021")

  idade_atual = ano_atual-nascimento
  idade_2022 = 2022 - nascimento

  return recebe_nome, idade_atual,idade_2022


def main():
    # Example usage
    nome, idade_atual, idade_2022 = idade()
    print(f"Olá, {nome}! Sua idade atual é: {idade_atual} anos.")
    print(f"Em 2022, você tinha {idade_2022} anos.")

if __name__ == "__main__":
    main()



